language: ruby
rvm:
  - 2.2.2

script: 
  - "bundle exec jekyll build"
  - "bundle exec htmlproofer ./_site --disable-external --allow-hash-href"  

after_script:
  - ./cloudflare_reset.sh
branches:
  only:
    - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  matrix:
  - secure: cgu7/wNdmZm6S5BE1Y3jZT52n1vMW6oD4LrM6yQOju62Gq/1+roL7sz9LwlBspZ8lG6UClPWceKPG4BE6v5WJINikA/ItiE7/56ViwCfJwzjwwAcNKo8RFro1ool+K3gYPaPl2pB2sNDJGaVF4gnwox6T9qKXzeUpPvKiRMh6CDZS0IX2+dnuf3aJ2CUaJXeMTSqw6WydSUsCPJuoi/MrBDD2N3JTX6mz844q/T/r8LVReCk4UXrvpRq9Xm7l91tptQODgii4NxFekYdgGctlMLzSQMcHwQ/bg5YezwIV/ym6VRkkpi7AMYNQZacdIPJ/RXpsuyQzmXaw6ELck18n6HzD1qAap+vhV5VLXLDhMIpe0hgn04NbGGcwnaO9xT9mPghk2w4LNcQIDdQhRHl4/O3yg7CF7uXwzDstyTzUH8F35rr7d4JL9u0aDzwXeZqjAt9yjhoR69DiE+UDjjxaBBBeqq7TqbG5LZodgIyCbJMhJrsecWpLXAbXTslxTbr5VKwISZWF/G1cpf/1AHXjbV2ozz1pjiduACFkhnW392Bf3D3gj/CG2RVic1KsW6NyTnvaBLx2AzyC55CBXtB6zxX3PustbZJ+Jm1uSIuRZ8uCRcRTDPMWQh8bsrfcRDIfG+UAUqMV0tkkSAwIo2q2OtqBtTNM8GFnq4tdRRnjOc=
  - secure: sho9cWIuKr19vXdUvoDHOodmxwY9Nn1/s8sLNb4U8JqA8JDF65QWwLJ5XR3xhSXXURkjsZK68IBh2KCyDXJGda3nyAbGMyLXkGA8A42W9JItbm/ELKPLyQfRF4gRhTiY2+s6SPY3X4cpCEz9bnoQ8XfI7wn99sLdOZxhCidag/VG11BFBdo241czHOEtgmryTyZODf4BTBHBrwlgYU+xL09DBhZmU7Di21MjtM+Qddl1D0m5/HCh0FTSNq1MQUWtfGM4yqCNpAv+am3rtp6xTtvI/MDeJvymKDl/W5stfBq6FESoxlF+5uevV7u9Y9AWSztHf77FhE8vKOVFsGhEHqcEQzXEfhKssJ5NERlW8HY13PZGaQGRePv+jlIv3OQi69YsFjkfQsGGo4YPK6ZZF6LkKHK5e8AajboOKNzhImEDWdZPRosTvr7tChkGeUw7BqLB/m66rHUHwPAomobgOVWmWJw08mxyP7L/G+qajwbKtsw3/SVTuTQUjkl8s64pSSYW1QHx762Rx7UqZSxxhsoc4GjyA9KNSNAsmIvhaCG3DfxmMOfyr4YFUBKDr9moYZnX/7b1LGSq/gtJfPlJmT0qBnBPtvyz09mjpkTLTqtzPI2orC1qVABNV67GtYtyhlPeNq3B9vj2Pwa7H6Suoc211bKBWbzKtvzpMdzqkzs=
