# Site settings
title: New England Herpetological Society 
email: webmaster@neherp.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.neherp.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
include: ['_pages', '_pages/projects', '_pages/guides']

# Put this on a different port so I can have expo and this site running at the same time
port: 4001
